force-app/main/default/objects/Project__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Tanggal Selesai Project</description>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Budget__c.field-meta.xml
<CustomField>
    <fullName>Project_Budget__c</fullName>
    <description>Budget dari sebuah project</description>
    <label>Project Budget</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Status__c</fullName>
    <description>Status dari suatu project (Active or Not-active)</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Belum Dimulai</fullName>
                <default>true</default>
                <label>Belum Dimulai</label>
            </value>
            <value>
                <fullName>Sedang Berjalan</fullName>
            </value>
            <value>
                <fullName>Selesai</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Tanggal mulai project</description>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ProjectHandler.cls
public class ProjectHandler {
    // Method untuk membuat Project baru
    public static Id createProject(String projectName, String status, Decimal budget, Date startDate, Date endDate) {
        Project__c newProject = new Project__c(
            Name = projectName,
            Project_Status__c  = status,
            Project_Budget__c = budget,
            Start_Date__c = startDate,
            End_Date__c = endDate
        );
        insert newProject;
        return newProject.Id;
    }
    
    // Method untuk memperbarui project
    public static void updateProject(Id projectId, String newStatus) {
        Project__c projectToUpdate = [Select Id, Project_Status__c FROM Project__c WHERE Id = :projectId LIMIT 1];
        ProjectToUpdate.Project_Status__c = newStatus;
        update projectToUpdate;
    }
    
    // Method untuk mengambil daftar project berdasarkan status
    public static List<Project__c> getProjectsByStatus(String status) {
        return [SELECT Id, Name, Project_Status__c, Start_Date__c, End_Date__c
                FROM Project__c
                WHERE Project_Status__c = :status];
    }
}