force-app/main/default/objects/Project__c/fields/Project_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Status__c</fullName>
    <description>Status dari suatu project (Active or Not-active)</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Belum Dimulai</fullName>
                <default>true</default>
                <label>Belum Dimulai</label>
            </value>
            <value>
                <fullName>Sedang Berjalan</fullName>
            </value>
            <value>
                <fullName>Selesai</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProjectHandlerTest.cls
@isTest
public class ProjectHandlerTest {
	@isTest
    static void testProjectHandler() {
        // membuat project baru
        Id projectId = ProjectHandler.createProject('IDStar Salesforce Bootcamp', 'Belum Dimulai', 500000000, Date.today(), Date.today().addDays(30));
        System.assertNotEquals(null, projectId, 'Project harus berhasil dibuat');
        
        // memperbarui project 
        ProjectHandler.updateProject(projectId, 'Selesai');
        Project__c updatedProject = [SELECT Project_Status__c FROM Project__c WHERE Id = :projectId];
        System.assertEquals('Selesai', updatedProject.Project_Status__c, 'Status harus menjadi Selesai');
        
        // mengambil daftar project
        List<Project__c> projects = ProjectHandler.getProjectsByStatus('Selesai');
        System.assert(projects.size() > 0, 'Harus ada project yang berstatus selesai');
    }
}