force-app/main/default/objects/Webinar_Ticket__c/Webinar_Ticket__c.object-meta.xml
<CustomObject>
    <label>Webinar Ticket</label>
    <nameField>
        <displayFormat>TICKET-{0000}</displayFormat>
        <label>Webinar Ticket Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Webinar Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Webinar_Ticket__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <label>Full Name</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webinar_Ticket__c/fields/Webinar_Name__c.field-meta.xml
<CustomField>
    <fullName>Webinar_Name__c</fullName>
    <label>Webinar Name</label>
    <referenceTo>Webinar__c</referenceTo>
    <relationshipLabel>Webinar Tickets</relationshipLabel>
    <relationshipName>Webinar_Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/WebinarApexRestAPI.cls
/**
 * @description       : 
 * @author            : npz
 * @group             : 
 * @last modified on  : 26-01-2025
 * @last modified by  : npz
**/
@RestResource(urlMapping='/Webinars/*')

global with sharing class WebinarApexRestAPI {
    @HttpGet
    global static Webinar_Ticket__c getWebinarById() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;

        String webinarId = req.requestURI.substring(req.requestURI.lastIndexOf('/') + 1);
        Webinar_Ticket__c webinarTicket = [Select Id, Webinar_Name__c, Phone__c, Full_Name__c, Email__c FROM Webinar_Ticket__c WHERE Id = :webinarId];
        return webinarTicket;
    }

    @HttpPost
    global static String createWebinarTicket(String fullName, String email, String phone, String webinarId){
        Webinar_Ticket__c webinar = new Webinar_Ticket__c (
            Full_Name__c = fullName,
            Email__c = email,
            Phone__c = phone,
            Webinar_Name__c = webinarId
        );
        insert webinar;
        return 'Webinar Ticket Created with ID: ' + webinar.Id;
    }
}