force-app/main/default/objects/Account/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Medium Business</fullName>
            </value>
            <value>
                <fullName>Small Business</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Revenue_Per_Employee__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Per_Employee__c</fullName>
    <label>Revenue Per Employee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AccountHandler.cls
public class AccountHandler {
    // Mengambil List/Array record object Account
    public static void assignCategory(List<Account> accounts) { 
        // Mengeluarkan record Account untuk di olah dan manipulasi
        for (Account acc : accounts) {
            if (acc.NumberOfEmployees < 50) {
                acc.Category__c = 'Small Business';
            } else if (acc.NumberOfEmployees >= 50 && acc.NumberOfEmployees <= 200) {
                acc.Category__c = 'Medium Business';
            } else if (acc.NumberOfEmployees > 200) {
                acc.Category__c = 'Enterprise';
            }
        }
    }
    
    // Mengambil List/Array record object Account
    public static void calculateRevenuePerEmployee(List<Account> accounts) {
        // Mengeluarkan record Account untuk di olah dan manipulasi
        for (Account acc : accounts) {
            if (acc.NumberOfEmployees != null && acc.NumberOfEmployees != 0 && acc.AnnualRevenue != null) {
                acc.Revenue_Per_Employee__c = acc.AnnualRevenue / acc.NumberOfEmployees;
            } else {
                acc.Revenue_Per_Employee__c = null; // Jika data tidak valid, set ke null
            }
        }
    }
}